<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- icone onglet -->
    <link rel="icon" type="image/png" href="../img/favicon.png">
    <!--normalize-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
	<!-- Font awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Barriecito&display=swap" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet"> 
	<!-- CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/index.css">
    <link rel="stylesheet" href="../css/form.css">
</head>
<body>
	<header>
		<div class="headBand">
			<nav class="navHeadBand wrapper">
				<a href="index.php" id="logo"><i class="fas fa-hamburger"></i> My Favorite Meal</a>
			</nav>
		</div>
		<p class="welcomeMessage wrapper">Bienvenue sur l'administration du site</p>
		<div class="lowHeadBand">
			<nav class="navlowHeadBand wrapper">
				<?php if ($title === 'Accueil de l\'administration du site !'): ?>
					<a class="headerNavButton" href="#toValidate">Les recettes à valider</a>
					<a class="headerNavButton" href="#searchRecipe">Rechercher une recette</a>
					<a class="headerNavButton" href="#editRecipe">Modifier une recette</a>
					<a class="headerNavButton" href="../index.php">myfavoritemeal.fr</a>
				<?php endif ?>
			</nav>
		</div>
	</header>
	<main>
		 <?= $content ?>
	</main>
	<footer>
		<nav class="navFooter wrapper">
			<a href="#"><i class="fab fa-facebook"></i></a>
			<a href="#"><i class="fab fa-twitter"></i></a>
			<a href="#"><i class="fab fa-instagram"></i></a>
			<a href="#"><i class="fab fa-youtube"></i></a>
			<a href="https://github.com/Nicolas151"><i class="fab fa-github"></i></a>
		</nav>		
	</footer>
<!-- jQuery versions 3.3.1 pour le bon fonctionnement de Bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 		crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js"
		integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
		crossorigin="anonymous"></script>
<script src="../js/index.js"></script>
<script src="../js/FormValidator.js"></script>
<script src="../js/utilities.js"></script>
</body>
</html>